config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :professors, controllers: {
    sessions:      'professors/sessions',
    passwords:     'professors/passwords',
    registrations: 'professors/registrations'
  }

  devise_scope :professor do
    post 'professors/guest_sign_in', to: 'professors/sessions#new_guest'
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  scope :professors do
    resources :professors
    resources :lectures do
      resources :lecture_details do
        resources :questions do
          resources :answers 
        end
        member do
         get :download
        end
      end
    end
  end


  scope :users do
    get 'subjects/search'
    resources :subjects, :schedules
      resources :lecture_details, only:[:show] do
        resources :submissions, :questions do
          member do
            get :download
          end
        end
      end
    resources :lecture_selects, only:[:search, :show] do
      collection do
        get 'search'
      end
    end
  end

end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user
  belongs_to :lecture_detail
  has_many   :answers

  with_options presence: true do
    validates :question_text
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @lecture_detail = LectureDetail.find(params[:lecture_detail_id])
    @question = Question.where(lecture_detail_id: params[:lecture_detail_id]).order(created_at: :desc)
  end

  def new
    @lecture_detail = LectureDetail.find(params[:id])
    @question_new = Question.new
  end

  def create
    @question_new = Question.new(question_params)
    if @question_new.save
      redirect_to action: :index 
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params_up)
      redirect_to action: :index
    else
      render :edit
    end
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.where(question_id: @question.id)
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to lecture_detail_questions_path(@question.lecture_detail_id)
  end

  private

  def question_params
    params.permit(:question_text).merge(user_id: current_user.id, lecture_detail_id: params[:lecture_detail_id])
  end

  def question_params_up
    params.require(:question).permit(:question_text).merge(user_id: current_user.id, lecture_detail_id: params[:lecture_detail_id])
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_new.html.erb
<%if user_signed_in? %>
<%= form_with model: @question_new, url: lecture_detail_questions_path(@lecture_detail.id), method: :POST, local: true  do |f| %>
  <div>質問フォーム</div><%= f.text_area :question_text, class: "question-text-area" %>
  <br>
  <%= f.submit "質問を投稿する" %>
<% end %>
<% end %>

app/views/questions/edit.html.erb
<div class="container-fluid">
<div class="question-title">Q&A</div>
<%= form_with model: @question, url: lecture_detail_question_path(@question, @question.lecture_detail_id, @question.id), local: true  do |f| %>
  <div>編集質問フォーム</div><%= f.text_area :question_text, class: "question-text-area-edit" %>
  <%= f.submit "編集する" %>
<% end %>
</div>

app/views/questions/index.html.erb
<div class="container-fluid">
  <div class="question-title">Q&A</div>
  <div>講義タイトル: <%= @lecture_detail.lecture_title_list %></div>
  <br>
  <%= render partial: "questions/new", locals: { question: @question } %>
  <br>
  <% @question.each do |f| %>
  <div class="question-list">
    <%= f.updated_at.to_s(:datetime_jp) %>
    <div>投稿者</div><%= f.user.name %>

    <% if professor_signed_in? %>
      <div class="question-content"><%= link_to f.question_text, lecture_lecture_detail_question_path(@question, f.lecture_detail_id, f.id) %></div>
    <% end %>

    <%if user_signed_in? %>
      <div class="question-content"><%= link_to f.question_text, lecture_detail_question_path(@question, f.id) %></div>
    <% if current_user.id == f.user_id %>
      <%= link_to '編集', edit_lecture_detail_question_path(@question, f.id), method: :get %>
      <%= link_to '削除', lecture_detail_question_path(@question, f.id), method: :delete %>
    <% end%>
    <% end%>
    <br>
  </div>
  <% end %>
</div>

app/views/questions/show.html.erb
<div class="container-fluid">
  <div class="answer-title">回答</div>
    <%= render partial: "answers/new", locals: { answer: @answer } %>
  <div>Q :</div>
  <div class="question-text"><%= @question.question_text %></div>
  <br>
  <div>A :</div>
  <% @answer.each do |f| %>
  <div class="answer-text"><%= f.answer_text%></div>
  <br>
    <% if professor_signed_in? %>
    <%= link_to '編集', edit_lecture_lecture_detail_question_answer_path(@answer, f.question_id, f.id), method: :get %>
    <%= link_to '削除', lecture_lecture_detail_question_answer_path(@answer, f.question_id, f.id), method: :delete %>
    <% end %>
  <br>
  <% end %>
</div>