config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :professors, controllers: {
    sessions:      'professors/sessions',
    passwords:     'professors/passwords',
    registrations: 'professors/registrations'
  }

  devise_scope :professor do
    post 'professors/guest_sign_in', to: 'professors/sessions#new_guest'
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  scope :professors do
    resources :professors
    resources :lectures do
      resources :lecture_details do
        resources :questions do
          resources :answers 
        end
        member do
         get :download
        end
      end
    end
  end


  scope :users do
    get 'subjects/search'
    resources :subjects, :schedules
      resources :lecture_details, only:[:show] do
        resources :submissions, :questions do
          member do
            get :download
          end
        end
      end
    resources :lecture_selects, only:[:search, :show] do
      collection do
        get 'search'
      end
    end
  end

end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user

  with_options presence: true do
    validates :title
    validates :start_time
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :schedules_set, only: [:edit, :update, :destroy]

  def new
    @schedules_new = Schedule.new
  end

  def create
    @schedules_new = Schedule.new(schedules_params)
    if @schedules_new.save
       redirect_to controller: :subjects, action: :index
    else
      render 'subjects/index'
    end
  end

  def edit
  end

  def update
    if @schedules.update(schedules_params_up)
      redirect_to controller: :subjects, action: :index
    else
      render :edit
    end
  end

  def destroy
    @schedules.destroy
    redirect_to controller: :subjects, action: :index
  end

  private

  def schedules_set
    @schedules = Schedule.find(params[:id])
  end

  def schedules_params
    params.permit(:start_time, :title, :text, :area, :time).merge(user_id: current_user.id)
  end

  def schedules_params_up
    params.require(:schedule).permit(:start_time, :title, :text, :area, :time).merge(user_id: current_user.id)
  end


end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_new.html.erb
<div class="container-fluid">
<div class="schedule-tilte">★近日のスケジュール</div>


<div class="d-flex justify-content-around">
<% schedules.first(8).each do |f| %>
<div class="card" style="width: 18rem; margin: 0 10px;">
  <div class="card-body">
    <h5 class="card-title"><%= f.start_time %> <%= "#{f.time.strftime('%H:%M')}" %></h5>
    <h6 class="card-subtitle mb-2 text-muted"><%= f.title %></h6>
    <p class="card-text"><%= f.text %></p>
    <p class="card-text"><%= f.area %></p>
  </div>
</div>
<% end%>
</div>
</div>

<div class="container-fluid">
<div class="mx-auto" style="width: 400px; margin: 40px;">
<div class="schedule-plan">★スケジュールの保存を行えます</div>
<%= form_with model: @schedules_new, url: schedules_path, method: :POST, local: true  do |f| %>
  <%= f.date_select :start_time, {use_month_numbers: true, start_year: 2020}, class:"reservation-select" %>
  <div>時間：</div><%= f.time_select :time %>
  <div>場所：</div><%= f.text_field :area, class: "schedule-field"%>
  <div>タイトル：</div><%= f.text_area :title, class: "schedule-field" %>
  <div>詳細：</div><%= f.text_area :text, class: "schedule-text"%>
  <br>
  <%= f.submit "予定を保存" %>
<% end %>
</div>
</div>

<div class="container-fluid">
<%= month_calendar events: schedules do |date, schedule| %>
  <%= date.day %>
  <% schedule.each do |f| %>
      <%= link_to f.title, edit_schedule_path(f.id),  method: :get, class: "text-primary" %>
  <% end %>
<% end %>
</div>

app/views/schedules/edit.html.erb
<h1>予定編集</h1>

<%= form_with model: @schedules, url: schedule_path do |f| %>
  <%= f.date_select :start_time, {use_month_numbers: true, start_year: 2020}, class:"reservation-select" %>
  <div>タイトル：</div><%= f.text_field :title %>
  <div>詳細：</div><%= f.text_field :text %>
  <div>場所：</div><%= f.text_field :area %>
  <div>時間：</div><%= f.time_select :time %>
  <br>
  <%= f.submit "予定変更" %>
  <%= link_to '削除', schedule_path(@schedules.id), method: :delete %>
<% end %>