config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :professors, controllers: {
    sessions:      'professors/sessions',
    passwords:     'professors/passwords',
    registrations: 'professors/registrations'
  }

  devise_scope :professor do
    post 'professors/guest_sign_in', to: 'professors/sessions#new_guest'
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  scope :professors do
    resources :professors
    resources :lectures do
      resources :lecture_details do
        resources :questions do
          resources :answers 
        end
        member do
         get :download
        end
      end
    end
  end


  scope :users do
    get 'subjects/search'
    resources :subjects, :schedules
      resources :lecture_details, only:[:show] do
        resources :submissions, :questions do
          member do
            get :download
          end
        end
      end
    resources :lecture_selects, only:[:search, :show] do
      collection do
        get 'search'
      end
    end
  end

end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :professor
  belongs_to :question

  with_options presence: true do
    validates :answer_text
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def new
    @answer_new = Answer.new
    @question = Question.find(params[:id])
  end

  def create
    @answer_new = Answer.new(answer_params)
    if @answer_new.save
      redirect_to  lecture_lecture_detail_question_path(id: @answer_new.question_id)
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
    @answer = Answer.find(params[:question_id])
  end

  def update
    @question = Question.find(params[:question_id])
    @answer = Answer.find(params[:id])
    @answer.update(answer_params_up)
    redirect_to lecture_lecture_detail_question_path(@question, @question.lecture_detail_id, @answer.question_id)
  end

  def destroy
    @answer = Answer.find(params[:question_id])
    @answer.destroy
    redirect_to lecture_lecture_detail_question_path(@answer, @answer.question_id)
  end

  private

  def answer_params
      params.permit(:answer_text).merge(professor_id: current_professor.id, question_id: params[:question_id])
  end

  def answer_params_up
    params.require(:answer).permit(:answer_text).merge(professor_id: current_professor.id, question_id: params[:question_id])
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_new.html.erb
<% if professor_signed_in? %>
  <div>回答フォーム</div>
  <%= form_with model:@answer_new, url: lecture_lecture_detail_question_answers_path(@question, @question.lecture_detail_id, @question.id), local: true do |f| %>
  <%= f.text_area :answer_text, class: "answer-text-area"%>
  <br>
  <%= f.submit '回答する' %>
<% end %>
<% end %>

app/views/answers/edit.html.erb
<div class="container-fluid">
<% if professor_signed_in? %>
  <div>回答編集フォーム</div>
  <%= form_with model:@answer, url: lecture_lecture_detail_question_answer_path(@question, @question.lecture_detail_id, @question.id, @answer.id), local: true do |f| %>
  <%= f.text_area :answer_text, class: "answer-text-area-edit" %>
  <%= f.submit '編集する' %>
<% end %>
<% end %>
</div>