config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  
  devise_for :professors, controllers: {
    sessions:      'professors/sessions',
    passwords:     'professors/passwords',
    registrations: 'professors/registrations'
  }

  devise_scope :professor do
    post 'professors/guest_sign_in', to: 'professors/sessions#new_guest'
  end

  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end
  
  scope :professors do
    resources :professors
    resources :lectures do
      resources :lecture_details do
        resources :questions do
          resources :answers 
        end
        member do
         get :download
        end
      end
    end
  end


  scope :users do
    get 'subjects/search'
    resources :subjects, :schedules
      resources :lecture_details, only:[:show] do
        resources :submissions, :questions do
          member do
            get :download
          end
        end
      end
    resources :lecture_selects, only:[:search, :show] do
      collection do
        get 'search'
      end
    end
  end

end

app/models/subject.rb
class Subject < ApplicationRecord
  belongs_to :user
  has_many :subject_details, dependent: :destroy
  accepts_nested_attributes_for :subject_details, allow_destroy: true

  with_options presence: true do
    validates :grade_genre_id
    validates :period_genre_id
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :search_product, only: [:show, :search, :edit]

  def index
    @schedules = Schedule.where(user_id: current_user.id).order(start_time: :asc)
  end

  def new
    @user = current_user
    @subject = Subject.new
    @subject_details = @subject.subject_details.build
    @subject_details = @subject.subject_details.build
    @subject_details = @subject.subject_details.build
  end

  def create
    @user = current_user
    @subject = Subject.new(subject_params)
   if @subject.save
     redirect_to subjects_path
   else
     render :new
   end
  end

  def show
    @subject_details = SubjectDetail.where(user_id: params[:id])
    @unit_sum = SubjectDetail.where(user_id: params[:id]).sum(:unit)
  end 

  def search
    @results = @p.result.where(user_id: current_user.id).includes(:subject) 
    @results_unit = @results.sum(:unit)
  end

  def edit
    @subject = Subject.where(user_id: params[:id]).includes(:subject_detail) 
  end

  def update
    
  end

  private

  def subject_params
    params.require(:subject).permit(:grade_genre_id, :period_genre_id, 
    subject_details_attributes: [:id, :user_id, :curriculum, :unit, :result_genre_id, :select_genre_id, :time_genre_id, :week_genre_id, :_destroy]).merge(user_id: current_user.id)
  end

  def search_product
    @p = SubjectDetail.ransack(params[:q])
  end

end

app/helpers/subjects_helper.rb
module SubjectsHelper
  
  def genre_select
    select_genre = ['0', '--', '必修科目','選択科目', 'その他']
  end

  def genre_time
    time_genre = ['0', '--','１限目', '２限目','３限目','４限目','５限目','６限目','７限目','その他']
  end

  def genre_result
    result_genre = ['0', '--','取得','落第','受講中' ]
  end

  def genre_week
    week_genre = ['0','--','月曜日','火曜日','水曜日','木曜日','金曜日','土曜日','日曜日']
  end


end

app/views/subjects/_subject_detail_fields.html.erb
<div class="nested-fields">
    <div class="registration", id="new_text" >

    <%= f.hidden_field :user_id, value:current_user.id %>

    <div class="block">
      <div class="curriculum-main">講義名
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.text_area :curriculum, class:"curriculum-text", id:"item-name", placeholder:"講義名を記載してください" %>
    </div>

    <div class="block">
      <div class="unit-main">単位
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.text_area :unit, class:"unit-text", id:"item-name", placeholder:"単位数" %>
    </div>

    <div class="block">  
      <div class="select-main">科目
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.select(:select_genre_id, SubjectDetail.select.map { |s| [s[:name], s[:id]] })%>
    </div>


    <div class="block"> 
      <div class="week-main">曜日
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.select(:week_genre_id, SubjectDetail.week.map { |s| [s[:name], s[:id]] })%>
    </div>

    <div class="block"> 
      <div class="time-main">何限
        <span class="indispensable">[必須]</span>
      </div>
      <%= f.select(:time_genre_id, SubjectDetail.time.map { |s| [s[:name], s[:id]] })%>
    </div>

    <div class="block"> 
      <div class="result-main">結果
        <span class="indispensable">[必須]</span>
      </div>
      <%= f.select(:result_genre_id, SubjectDetail.result.map { |s| [s[:name], s[:id]] })%>
    </div>
    <%= link_to_remove_association '削除', f, class: 'registration-delete' %>
</div>

app/views/subjects/edit.html.erb
<%= form_for @subject, local: true do |f| %>
  <div class="grade-period">
    <div class="block">
        <div class="grade-main">学年
          <span class="indispensable">[必須]</span>
        </div>
        <%= f.select(:grade_genre_id, SubjectDetail.grade.map { |s| [s[:name], s[:id]] })%>
    </div>

    <div class="block">
        <div class="period-main">時期
          <span class="indispensable">[必須]</span>
        </div>
        <%= f.select(:period_genre_id, SubjectDetail.period.map { |s| [s[:name], s[:id]] })%>
    </div>

  <div class="nested-fields">
    <div class="registration", id="new_text" >

    <%= f.hidden_field :user_id, value:current_user.id %>

    <div class="block">
      <div class="curriculum-main">教材名
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.text_area :curriculum, class:"curriculum-text", id:"item-name", placeholder:"教材名を記載してください" %>
    </div>

    <div class="block">
      <div class="unit-main">単位
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.text_area :unit, class:"unit-text", id:"item-name", placeholder:"単位数" %>
    </div>

    <div class="block">  
      <div class="select-main">科目
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.select(:select_genre_id, SubjectDetail.select.map { |s| [s[:name], s[:id]] })%>
    </div>


    <div class="block"> 
      <div class="week-main">曜日
        <span class="indispensable">[必須]</span>
      </div>
        <%= f.select(:week_genre_id, SubjectDetail.week.map { |s| [s[:name], s[:id]] })%>
    </div>

    <div class="block"> 
      <div class="time-main">何限
        <span class="indispensable">[必須]</span>
      </div>
      <%= f.select(:time_genre_id, SubjectDetail.time.map { |s| [s[:name], s[:id]] })%>
    </div>

    <div class="block"> 
      <div class="result-main">結果
        <span class="indispensable">[必須]</span>
      </div>
      <%= f.select(:result_genre_id, SubjectDetail.result.map { |s| [s[:name], s[:id]] })%>
    </div>
    <%= link_to_remove_association '削除', f, class: 'registration' %>
</div>
   
<% end %>

app/views/subjects/index.html.erb
<div class="d-flex justify-content-around" style="margin-top: 50px; margin-left: 90px;">
  <div class="my-box w-25">
    <div class="card" style="width: 18rem;">
    <%= image_tag "subject-new.jpg", size: "286x180" %>
      <div class="card-body">
        <h5 class="card-title">・教材の登録を行えます！</h5>
        <p class="card-text">学年と時期に合わせて、科目や単位、曜日など登録を行うことができ、教材管理ができます。</p>
        <%= link_to '教材登録', new_subject_path, metod: :get, class: "btn btn-primary" %>
      </div>
    </div>
  </div>


  <div class="my-box w-25">
    <div class="card" style="width: 18rem;">
      <%= image_tag "subject.jpg", size: "286x180" %>
      <div class="card-body">
        <h5 class="card-title">・登録した教材を確認できます！</h5>
        <p class="card-text">学年と時期によって、登録した教材の確認、単位の合計等確認できます。</p>
        <%= link_to '教材登録一覧表', subject_path(current_user.id), class: "btn btn-primary" %>
      </div>
    </div>
  </div>

  <div class="my-box w-25">
    <div class="card" style="width: 18rem;">
      <%= image_tag "search.jpg", size: "286x180" %>
      <div class="card-body">
        <h5 class="card-title">・講義の検索を行えます！</h5>
        <p class="card-text">教授が登録した講義、講義内容、講義で使用した資料の確認、提出物の提出やQ＆Aも行えます。</p>
        <%= link_to '講義検索', search_lecture_selects_path, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

    <%#= link_to '教材登録', new_subject_path, metod: :get, class: 'subject-title' %>
    <%#= link_to '教材登録一覧表', subject_path(current_user.id), class: 'subject-botton'%>
    <%#= link_to '講義検索', search_lecture_selects_path, class: 'subject-botton'%>

<%= render partial: "schedules/new", locals: { schedules: @schedules } %>

app/views/subjects/new.html.erb
<div class="container-fluid">
  <div class="subject-new">
    <div class="university-main">大学名: <%= @user.university %></div>
    <div class="university-main">学部:  <%= @user.undergraduate %></div>
    <div class="university-main">学科:  <%= @user.department %></div>
  </div>
  <div class="subject-registration-main">講義等の登録をしてください</div>

  <%= form_for @subject, local: true do |f| %>
    <div class="grade-period">
      <div class="block">
        <div class="grade-main">学年<span class="indispensable">[必須]</span></div>
        <%= f.select(:grade_genre_id, SubjectDetail.grade.map { |s| [s[:name], s[:id]] })%>
      </div>

      <div class="block">
        <div class="period-main">時期<span class="indispensable">[必須]</span></div>
        <%= f.select(:period_genre_id, SubjectDetail.period.map { |s| [s[:name], s[:id]] })%>
      </div>
  
      <%= f.fields_for :subject_details do |subject_detail_fields| %>
        <%= render 'subject_detail_fields', f: subject_detail_fields %>
      <% end %>
      <div class="links">
        <%= link_to_add_association '追加', f, :subject_details %>
      </div>
      <div class="sell-btn-contents">
        <%= f.submit "保存" ,class:"sell-btn" %>
        <%#=link_to '戻る', subjects_path, class:"back-btn" %>
      </div>
      
  <% end %>
</div>

app/views/subjects/search.html.erb
<div class="container-fluid">
  <div class="result-title">検索結果　講義一覧</div>
  <%# 検索結果の個数で条件分岐 %>
  <div class="results-unit-sum"><%= "単位合計" %><%= @results_unit %></div>
  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">講義名</th>
        <th scope="col">単位</th>
        <th scope="col">科目</th>
        <th scope="col">曜日</th>
        <th scope="col">何限</th>
        <th scope="col">結果</th>
      </tr>
    </thead>
    <% if @results.length !=0 %>
    <% @results.each do |result| %>
      <tbody>
        <tr>
          <td><%= result.curriculum %></td>
          <td><%= result.unit %></td>
          <td><%= genre_select[result.select_genre_id] %></td>
          <td><%= genre_week[result.week_genre_id] %></td>
          <td><%= genre_time[result.time_genre_id] %></td>
          <td><%= genre_result[result.result_genre_id] %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
  <% else %>
  該当する教材はありません
  <% end %>
</table>
<br>
<%= link_to 'トップページへ戻る', subjects_path, metod: :get %>
</div>

app/views/subjects/show.html.erb
<div class="container-fluid">
  <h1>教材登録一覧</h1>
  <%= search_form_for @p, url: subjects_search_path do |f| %>
    <%= f.label :subject_grade_genre_id_eq, '学年：' %>
    <%= f.select(:subject_grade_genre_id_eq, SubjectDetail.grade.map { |s| [s[:name], s[:id]] }) %>
    <br>
    <%= f.label :subject_period_genre_id_eq, '期間：' %>
    <%= f.select(:subject_period_genre_id_eq, SubjectDetail.period.map { |s| [s[:name], s[:id]] })%>
    <br>
    <%= f.submit '検索' %>


      <%#= link_to '教材の更新・編集', edit_subject_path(f.id), method: :get %>
      <br>
      <div class="unit-sum"><%= "単位 総合計" %> <%= @unit_sum %></div>
      

    <table class="table">
      <thead class="thead-dark">
       <tr>
        <th scope="col">講義名</th>
        <th scope="col">単位</th>
        <th scope="col">科目</th>
        <th scope="col">曜日</th>
        <th scope="col">何限</th>
        <th scope="col">結果</th>
       </tr>
      </thead>
    <% @subject_details.each do |ff| %>
      <tbody>
        <tr>
          <td><%= ff.curriculum %></td>
          <td><%= ff.unit %></td>
          <td><%= genre_select[ff.select_genre_id] %></td>
          <td><%= genre_week[ff.week_genre_id] %></td>
          <td><%= genre_time[ff.time_genre_id] %></td>
          <td><%= genre_result[ff.result_genre_id] %></td>
        </tr>
      </tbody>
    <% end %>
    </table>
    
<% end %>
</div>